import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CircleAlert, Clock3, ExternalLink, RotateCcw, ShieldCheck, TimerReset, X } from "lucide-react";
import { scoreAssessment } from "../data/assessments";

function Progress({current,total}){return <div className="assessment-progress" aria-label={`Step ${current} of ${total}`}><span style={{width:`${current/total*100}%`}}/></div>}

export default function AssessmentStudio({assessment,existing,onClose,onComplete}){
  const [stage,setStage]=useState(existing?"result":"intro"),[step,setStep]=useState(0),[answers,setAnswers]=useState({}),[memorySeen,setMemorySeen]=useState(false),[timer,setTimer]=useState(0),[running,setRunning]=useState(false);
  const closeRef=useRef(null); const result=useMemo(()=>stage==="result"?(existing||scoreAssessment(assessment.id,answers)):null,[stage,existing,assessment.id,answers]);
  useEffect(()=>{closeRef.current?.focus();const key=e=>e.key==="Escape"&&onClose();window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[onClose]);
  useEffect(()=>{if(!running)return;const id=setInterval(()=>setTimer(value=>value+1),1000);return()=>clearInterval(id)},[running]);
  const question=assessment.questions[step]; const total=assessment.questions.length;
  const canContinue=question?.optionalWhen&&Number(answers[question.optionalWhen])===1||answers[question?.id]!==undefined&&answers[question?.id]!=="";
  function next(){if(step<total-1){setStep(step+1)}else{const scored=scoreAssessment(assessment.id,answers);onComplete(assessment.id,{...scored,completedAt:new Date().toISOString(),answers});setStage("result")}}
  function restart(){setAnswers({});setStep(0);setMemorySeen(false);setTimer(0);setRunning(false);setStage("intro")}
  return <div className="assessment-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="assessment-studio" role="dialog" aria-modal="true" aria-labelledby="assessment-title"><button ref={closeRef} className="assessment-close" onClick={onClose} aria-label="Close assessment"><X/></button>
    <div className="studio-brand"><span>{assessment.short}</span><small>{assessment.source}</small></div>
    {stage==="intro"&&<div className="studio-intro"><span className="eyebrow">EVIDENCE-BASED SCREEN</span><h2 id="assessment-title">{assessment.title}</h2><p>{assessment.intro}</p>{assessment.safety&&<div className="safety-note"><CircleAlert/><span><strong>Safety first</strong>Place the chair against a wall. Do not perform this alone if you have fallen recently or feel unsteady.</span></div>}<div className="studio-facts"><span><Clock3/>{assessment.time}</span><span><ShieldCheck/>Private on this device</span></div><button className="primary-button studio-primary" onClick={()=>setStage(assessment.memoryWords?"memory":"questions")}>Begin check <ArrowRight/></button><a href={assessment.sourceUrl} target="_blank" rel="noreferrer">Read the source methodology <ExternalLink/></a></div>}
    {stage==="memory"&&<div className="memory-stage"><span className="eyebrow">MEMORY STEP</span><h2 id="assessment-title">Remember these three words</h2><p>Say each word aloud. You will be asked to recall them after another question.</p><div className="memory-words">{assessment.memoryWords.map(word=><strong key={word}>{word}</strong>)}</div><button className="primary-button studio-primary" onClick={()=>{setMemorySeen(true);setStage("questions")}}>I have memorised them <ArrowRight/></button></div>}
    {stage==="questions"&&question&&<div className="studio-question"><Progress current={step+1} total={total}/><span className="eyebrow">QUESTION {step+1} OF {total}</span><h2 id="assessment-title">{question.text}</h2>{question.id==="recall"&&memorySeen&&<p className="question-hint">Do not scroll back. Choose what you remembered before seeing the words again.</p>}
      {question.type==="choice"&&<div className="answer-list">{question.options.map(option=><button key={option.label} className={answers[question.id]===option.value?"selected":""} onClick={()=>setAnswers({...answers,[question.id]:option.value})}><span>{option.label}</span><i>{answers[question.id]===option.value&&<Check/>}</i></button>)}</div>}
      {question.type==="number"&&assessment.id==="mobility"&&Number(answers[question.optionalWhen])!==1&&<><div className="chair-timer"><button className={running?"running":""} onClick={()=>setRunning(!running)}><TimerReset/><strong>{timer}s</strong><span>{running?"Pause timer":"Start timer"}</span></button><div><label>Or enter your result<input type="number" min={question.min} max={question.max} value={answers[question.id]??(timer||"")} onChange={e=>setAnswers({...answers,[question.id]:Number(e.target.value)})}/><span>{question.unit}</span></label>{timer>0&&<button className="use-time" onClick={()=>{setAnswers({...answers,[question.id]:timer});setRunning(false)}}>Use {timer} seconds</button>}</div></div></>}
      {question.type==="number"&&assessment.id!=="mobility"&&<label className="simple-measure"><input autoFocus type="number" min={question.min} max={question.max} step="0.1" value={answers[question.id]??""} onChange={e=>setAnswers({...answers,[question.id]:Number(e.target.value)})}/><span>{question.unit}</span></label>}
      {question.type==="number"&&Number(answers[question.optionalWhen])===1&&<div className="safety-note"><ShieldCheck/><span><strong>Good decision</strong>We will record that a supported assessment is safer for you. Do not attempt the test alone.</span></div>}
      <div className="studio-nav">{step>0&&<button className="back-button" onClick={()=>setStep(step-1)}><ArrowLeft/>Back</button>}<button className="primary-button" disabled={!canContinue} onClick={next}>{step===total-1?"See my result":"Continue"}<ArrowRight/></button></div></div>}
    {stage==="result"&&result&&<div className="studio-result"><div className={`result-mark ${result.level}`}><Check/></div><span className="eyebrow">YOUR SCREENING RESULT</span><h2 id="assessment-title">{result.label}</h2>{result.score!==null&&<div className="result-score"><strong>{result.score}</strong>{result.max&&<span> / {result.max}</span>}</div>}<p>{result.summary}</p><div className="result-action"><strong>Your next best step</strong><span>{result.action}</span></div><div className="result-caveat"><CircleAlert/>A screening result is not a diagnosis. Seek professional care for new, worsening or concerning symptoms.</div><div className="studio-nav"><button className="back-button" onClick={restart}><RotateCcw/>Take again</button><button className="primary-button" onClick={onClose}>Done <Check/></button></div></div>}
  </section></div>
}

