name: Deploy to Testing Server

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script on testing server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.TEST_SERVER_IP }}
          username: ${{ secrets.TEST_SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/ooglobe/scripts
            sed -i 's/\r$//' deploy_sledss_test.sh
            chmod +x deploy_sledss_test.sh
            ./deploy_sledss_test.sh
